services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Dockerfile.app
    restart: always
    depends_on:
      - redis
      - pgsql
    networks:
      - default
      - internal
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - UPLOAD_DIR=/app/upload
      - TRAEFIK_CONFIG_DIR=/data/traefik
      - DOCKER_HOST=tcp://docker-proxy:2375
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${HOSTNAME:-localhost}`)"
      - "traefik.http.routers.app.service=app@docker"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.docker.network=devpush_default"
      - "traefik.http.routers.app.entrypoints=web"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - internal

  docker-proxy:
    container_name: docker-proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
      - POST=1
      - EXEC=1
      - NETWORKS=1
      - DISABLE_IPV6=1
    networks:
      - internal

  traefik:
    image: traefik:v3.3.2
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - default
      - internal
    labels:
      - "traefik.enable=true"

  runner:
    image: runner
    build:
      context: ./Docker
      dockerfile: Dockerfile.runner
    profiles: ["build-only"]
    dns:
      - 8.8.8.8
      - 8.8.4.4

  pgsql:
    container_name: pgsql
    image: postgres:16
    restart: always
    networks:
      - internal
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    env_file:
      - .env
    volumes:
      - devpush-db:/var/lib/postgresql/data

volumes:
  devpush-db:

networks:
  default:
    name: devpush_default
  internal:
    name: devpush_internal
    internal: true